"""add roadmap and roadmap task tables

Revision ID: 27ee281913b3
Revises: cdec70f0150a
Create Date: 2026-06-12 23:55:09.231643
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '27ee281913b3'
down_revision: Union[str, None] = 'cdec70f0150a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
