"""Add preferences to user

Revision ID: cdec70f0150a
Revises: d38bb87553f7
Create Date: 2026-06-10 15:21:17.174497
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cdec70f0150a'
down_revision: Union[str, None] = 'd38bb87553f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
