"""add preferences to user

Revision ID: d38bb87553f7
Revises: 
Create Date: 2026-06-10 14:58:19.434058
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd38bb87553f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('input_mode', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('agents_used', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('color', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('icon', sa.String(length=10), nullable=True))
    op.add_column('session_memory', sa.Column('topics', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('mode', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('user_memory', sa.Column('memory_type', sa.String(length=50), nullable=True))
    op.add_column('user_memory', sa.Column('source_session_id', sa.UUID(), nullable=True))
    op.add_column('user_memory', sa.Column('source_voice_session_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('user_memory', 'source_voice_session_id')
    op.drop_column('user_memory', 'source_session_id')
    op.drop_column('user_memory', 'memory_type')
    op.drop_column('sessions', 'is_pinned')
    op.drop_column('sessions', 'mode')
    op.drop_column('session_memory', 'topics')
    op.drop_column('projects', 'icon')
    op.drop_column('projects', 'color')
    op.drop_column('messages', 'response_time')
    op.drop_column('messages', 'agents_used')
    op.drop_column('messages', 'transcript')
    op.drop_column('messages', 'input_mode')
    # ### end Alembic commands ###
